package com.dgrdm9.menulist.Utilities;

import com.dgrdm9.menulist.Models.Evento;

import java.util.ArrayList;
import java.util.List;

public class Util {

    public static List<Evento> setPrehEventos() {
        List<Evento> eventoList = new ArrayList<>();
        eventoList.add(new Evento("Alrededor de 3000 a. C. ", "-Se inventa el ábaco (en Babilonia), primera \"máquina\" para realizar cáculos."));
        eventoList.add(new Evento("1617", "-John Napier inventa sus varillas de numeración (o huesos de Napier)."));
        eventoList.add(new Evento("1622", "-William Oughtred inventa la regla de cálculo circular basándose en los logaritmos de Napier."));
        eventoList.add(new Evento("1642-1643", "-Blaise Pascal inventa y fabrica una sumadora mecánica llamada la Pascalina."));
        eventoList.add(new Evento("1673", "-Gottfried Wilhelm Leibniz diseña y construye una máquina mecánica para realizar cálculos aritméticos. El sistema diseñado por Leibniz se usó en años posteriores para fabricar calculadoras mecánicas."));
        eventoList.add(new Evento("1801", "-El mecánico francés Joseph-Marie Jacquard inventa un telar de tapices controlado por un sistema de tarjetas perforadas."));
        eventoList.add(new Evento("1822", "-Charles Babbage presenta su proyecto de la máquina diferencial, para evaluar polinomios."));
        eventoList.add(new Evento("1834", "-Babbage diseña la Máquina Analítica, ingenio mecánico que puede realizar cualquier tipo de operación matemática siguiendo las instrucciones contenidas en unas tarjetas perforadas."));
        eventoList.add(new Evento("1842-1843", "-Augusta Ada King, Condesa de Lovelace, propone las primeras ideas de programación sobre la máquina analítica de Babbage."));
        eventoList.add(new Evento("1844", "-Morse envía el primer mensaje telegráfico entre Washington y Baltimore."));
        eventoList.add(new Evento("1854", "-George Boole publica su trabajo “Una investigación de las leyes del pensamiento”, que constituiría las bases del diseño de computadores."));
        eventoList.add(new Evento("1889", "-Herman Hollerith construye la máquina censadora o tabuladora, que por medio de tarjetas perforadas reducía el tiempo al realizar el censo de América."));
        eventoList.add(new Evento("1904", "-John Fleming patenta los diodos de vacío."));
        eventoList.add(new Evento("1906", "-Lee De Forest inventa las válvulas, añadiendo un tercer electrodo a los diodos de Fleming."));
        eventoList.add(new Evento("1919", "-Los físicos Eccles y Jordan inventan el circuito electrónico de conmutación “flip-flop”."));
        eventoList.add(new Evento("1924", "-Thomas J. Watson renombra el empresa CTR, por International Business Machines (IBM)"));
        eventoList.add(new Evento("1937", "-Alan Turing publica su artículo “On Computable Numbers”, donde plantea las ideas de su conocida máquina."));
        eventoList.add(new Evento("1938", "-William Hewlett y David Packard constituyen la compañía Hewlett-Packard (HP) en Palo Alto, California.\n\n-Konrad Zuse, en Alemania, completa la construcción de su computador mecánico binario “Z1”."));
        eventoList.add(new Evento("1939", "-John Vicent Atanasoff y su estudiante Clifford E. Berry construyen un prototipo de computador electrónico digital que utiliza aritmética binaria."));
        eventoList.add(new Evento("1940", "-Konrad Zuse completa en Alemania la construcción de su computador electromecánico “Z2”, basado en relés de telefonía."));
        eventoList.add(new Evento("1941", "-Konrad Zuse construye en Alemania su computador “Z3”, el primer computador digital electromecánico controlado por un programa."));
        eventoList.add(new Evento("1944", "-Alan Turing y otros compañeros construyen en Gran Bretaña el “Colossus”, primer computador electrónico construido con válvulas. Se destinó al descifrado de los mensajes alemanes en código Enigma.\n\n-Howard Aiken en la Universidad de Harvard pone en funcionamiento el “Mark I”."));
        eventoList.add(new Evento("1945", "-John Presper Eckert y John Mauchly firman un contrato para construir el “EDVAC”.\n\n-John von Neumann introduce el concepto de programa almacenado.\n\n-Grace Murray Hopper mientras trabajaba en el prototipo del “Mark II”, observa un fallo en un relé causado por una polilla, este hecho le lleva a popularizar el término “bug”."));
        return eventoList;
    }

    public static List<Evento> setFirstEventos() {
        List<Evento> eventoList = new ArrayList<>();
        eventoList.add(new Evento("1946", "-John Presper Eckert y John Mauchly ponen en funcionamiento en la Universidad de Pensilvania el “ENIAC”, el primer ordenador de propósito general, que era 500 veces más rápido que las calculadoras electromecánicas.\n\n-John von Neumann, Herman Goldstine y Arthur Burks publican el informe “Preliminary Discusión of the Logical Design of an Electronic Computing Instrument”, donde exponen las ideas básicas en que se apoya el cálculo digital electrónico.\n\n-Alan Turing publica un informe en el que caracteriza la extracción aleatoria de información sobre la máquina Automatic Computing Engine (ACE)."));
        eventoList.add(new Evento("1947", "-Howard Aiken y su equipo completan el “Mark II”.\n\n-John Bardeen, Walter Brattain y William Schockley, de los laboratorios Bell, inventan el transistor."));
        eventoList.add(new Evento("1948", "-Richard Hammnig propone su método para encontrar y corregir errores en bloques de datos.\n\n-IBM presenta el “SSEC”, primera máquina que incorpora la noción de programa almacenado de Von Neuman."));
        eventoList.add(new Evento("1949", "-Maurice Wilkes en la Universidad de Cambridge (UK) construye el “EDSAC”, que sigue las ideas de programa almacenado.\n\n-John Mauchly desarrolla el Short Order Code, que puede ser considerado el primer lenguaje de programación del alto nivel."));
        eventoList.add(new Evento("1951", "-Se lanza al mercado el Universal Automatic Computer (UNIVAC I)\n\n-Aparecen las “cintas magnéticas” como soporte de almacenamiento de la información.\n\n-William Shockey inventa el transistor de unión.\n\n-Maurice Wilkes introduce la idea de Microprogramación, una técnica para facilitar el diseño de la unidad de control.\n\n-Grace Murray Hopper desarrolla el primer compilador, el A-0."));
        eventoList.add(new Evento("1952", "-El UNIVAC I predice la elección del presidente norteamericano Dwight Eisenhower antes del cierre de los colegios electorales.\n\n-Aparece en el mercado el IBM 701, capaz de ejecutar 17.000 instrucciones por segundo.\n\n-Thomas Watson Jr. es nombrado presidente de la compañía IBM.\n\n-Se construye el ILLIAC I"));
        eventoList.add(new Evento("1953", "-Se comercializa el IBM 650, considerado el primer computador producido en serie."));
        eventoList.add(new Evento("1954", "-Texas Instruments comercializa el primer transistor de silicio.\n\n-Se lanzan al mercado el IBM 704 y el UNIVAC 1103A, primeras máquinas que utilizaban memoria de ferritas.\n\n-Se comercializan las unidades de cinta magnética como dispositivos de lectura/escritura."));
        return eventoList;
    }

    public static List<Evento> setSecondEventos() {
        List<Evento> eventoList = new ArrayList<>();
        eventoList.add(new Evento("1956", "-IBM desarrolla el 350 RAMAC (Random Access Method of Accounting and Control), el primer sistema de almacenamiento basado en discos magnéticos.\n\n-Reciben el Premio Nobel de Física Shockley, Brattain y Bardeen, inventores del transistor.\n\n-John McCarthy y Marvin Minsky introducen el concepto de “Inteligencia Artificial”."));
        eventoList.add(new Evento("1957", "-John Backus y su equipo desarrollan en IBM, el primer compilador de FORTRAN (FORmula TRANslator) para desarrollo de aplicaciones científicas.\n\n-La Unión Soviética pone en órbita el Sputnik I, primer satélite artificial de la historia. Este hecho marca el comienzo de la “carrera espacial”.\n\n-Los Estados Unidos crean la agencia ARPA (Advanced Research Projects Agency) en respuesta al lanzamiento del Sputnik I.\n\n-John McCarthy forma el Departamento de Inteligencia Artificial en el MIT (USA)."));
        eventoList.add(new Evento("1958", "-Jack Kilby de Texas Instruments y Robert Noyce, de Fairchild Semiconductors, trabajando separadamente, desarrollan un prototipo de circuito integrado.\n\n-La compañía Bell desarrolla el MODEM (MOdulator-DEModulator), artefacto que permite transmitir datos binarios digitales por la línea telefónica analógica convencional."));
        eventoList.add(new Evento("1959", "-John MacCarthy desarrolla el lenguaje LISP (LISt Processing), ideado para aplicaciones de inteligencia artificial.\n\n-Se desarrolla el lenguaje COBOL.\n\n-NEC presenta en la feria de París el NEAC 2201, el primer computador comercial totalmente transistorizado.\n\n-Xerox introduce en el mercado la primera fotocopiadora.\n\n-Robert Noyce y Gordon Moore solicitan una patente sobre su tecnología desarrollada para realizar circuitos integrados."));
        eventoList.add(new Evento("1960", "-Paul Baran desarrolla el principio de conmutación de paquetes para transmisión de datos.\n\n-Se desarrolla el ALGOL-60, primer lenguaje que introdujo la programación estructurada.\n\n-Bull lanza el GAMMA 60, con capacidad de funcionamiento de multiprogramación.\n\n-Kang y Atalla, de los laboratorios Bell, construyen el primer transistor MOS."));
        eventoList.add(new Evento("1961", "-Se comercializan los ordenadores de alta velocidad: IBM 7030, UNIVAC 1107, HONEYWELL 800, CDC 3600 y ATLAS.\n\n-Georg C. Devol patenta un dispositivo robótico que comercializará Unimation como el primer robot industrial. Se utilizó en la manufactura de tubos de TV.\n\n-Fairchild Semiconductors comercializa el primer circuito integrado."));
        eventoList.add(new Evento("1962", "-Max V. Mathews lidera un grupo en los laboratorios Bell que desarrolla un software capaz de sintetizar, almacenar y editar música.\n\n-Steve Russell, estudiante del MIT, desarrolla el primer videojuego, Spacewar!."));
        eventoList.add(new Evento("1963", "-El American National Standard Institute acepta el código ASCII de 7 bits para intercambio de información.\n\n-Se construye el sistema SAGE (Semi-Automated Ground Environment) para defensa militar."));
        return eventoList;
    }

    public static List<Evento> setThirdEventos() {
        List<Evento> eventoList = new ArrayList<>();
        eventoList.add(new Evento("1964", "-Gordon Moore, fundador de Intel, predice que el número de componentes de un circuito integrado se duplicaría cada 18 meses, predicción conocida posteriormente como la Ley de Moore.\n\n-John Kemeny y Thomas E. Kurtz desarrollan el lenguaje BASIC en el Dartmouth College.\n\n-IBM lanza el sistema 360, primera línea de computadores compatibles.\n\n-Douglas Engelbart inventa el ratón.\n\n-Sale al mercado el CDC 6600, diseñado por Seymour Cray y considerado el primer supercomputador comercial, alcanzaba velocidades de 9 megaflops."));
        eventoList.add(new Evento("1965", "-DEC lanza el primer minicomputador, el PDP-8.\n\n-IBM patenta la idea de construir memorias RAM dinámicas basadas en celdas de un único transistor.\n\n-El proyecto MAC propicia el desarrollo del sistema operativo MULTICS.\n\n-Maurice Wilkes propone el uso de memorias cache.\n\n-Se pone en el mercado el UNIVAC 1108, primer computador multiprocesador.\n\n-Se presenta el primer plan de ARPANET, una red de ordenadores militares y de instituciones estadounidenses."));
        eventoList.add(new Evento("1967", "-Ole-Johan Dahl y Kisten Nygaard desarrollan el SIMULA 67, primer lenguaje orientado a objetos.\n\n-Jack Kilb, Jerry Merryman y James van Tassel en Texas Instruments inventan la calculadora de mano, con capacidad para realizar las cuatro operaciones básicas.\n\n-Donald Knuth escribe sobre los algoritmos y estructuras de datos como entidades separadas de los programas en los que son usados."));
        eventoList.add(new Evento("1968", "-En una conferencia financiada por el comité de ciencia de la NATO sobre la “crisis del software” se introduce el término ingeniería del software.\n\n-Las máquinas de Burroughs B2500 y B3500 son las primeras en incorporar circuitos integrados.\n\n-Se plantea la norma de utilizar formatos de 6 dígitos (YYMMDD) para la fechas, decisión que posteriormente daría lugar a la “crisis del año 2000”.\n\n-Robert Noyce, Andy Grove y Gordon Moore forman la compañía Intel.\n\n-Seymour Cray diseña el supercomputador CDC 7600, que alcanza velocidades de 40 megaflops.\n\n-Se comercializa el “IBM 360/85”, primer ordenador con “Memoria Cache”."));
        eventoList.add(new Evento("1969", "-Se comercializa el “IBM 360/85”, primer ordenador con “Memoria Cache”.\n\n-Se establecen los primeros 4 nodos de ARPANET, en las universidades de UCLA, Stanford Research Institute (SRI), UC en Santa Bárbara y Utah.\n\n-Se introduce el estándar RS-232-C para facilitar el intercambio de datos entre computadores y periféricos.\n\n-Se introduce el estándar RS-232-C para facilitar el intercambio de datos entre computadores y periféricos."));
        eventoList.add(new Evento("1970", "-Ken Thompson y Dennis Ritchie, de los laboratorios Bell, compilan la primera versión de UNIX.\n\n-IBM desarrolla e introduce el disco flexible de 8 pulgadas, el precursor de los modernos disquetes.\n\n-Niklaus Wirth desarrolla el PASCAL, que en 1972 dará lugar al MODULA 2.\n\n-Se anuncia la nueva serie de ordenadores “IBM 370”."));
        return eventoList;
    }

    public static List<Evento> setForthEventos() {
        List<Evento> eventoList = new ArrayList<>();
        eventoList.add(new Evento("1971", "-Ted Hoff, Stan Mazor y Federico Fagin desarrollan el microprocesador Intel 4004, un computador en un único chip, que contiene 2.300 transistores y funciona a 108 kHz.\n\n-Ray Tomlinson, de Bolt Beranek y Newman, envía el primer correo electrónico de la historia y define el uso de la arroba (@) para separar los campo del destinatario y de la máquina receptora.\n\n-Se comercializa la serie de ordenadores “UNIVAC 1100”."));
        eventoList.add(new Evento("1972", "-Aparece la primera calculadora programable de bolsillo HP-35, dejando a la regla de cálculo obsoleta.\n\n-Intel diseña el 8008, primer microprocesador de 8 bits con 3.500 transistores y una velocidad de 108 kHz.\n\n-Nolan Bushnell diseña el videojuego Pong. Posteriormente fundaría la compañía ATARI.\n\n-Dennis Ritchie, en los laboratorios Bell crea el C, lenguaje que describe casi todo el UNIX y sus herramientas.\n\n-Wang, VYDEC y Lexitron introducen los sistemas de procesado de textos."));
        eventoList.add(new Evento("1973", "-Robert Metcalf plantea la red Ethernet como una modificación a la red Alohanet.\n\n-Xerox desarrolla el prototipo de computador personal ALTO, dotado de ratón, conexión Ethernet e interfaz gráfica de usuario.\n\n-La técnica de integración LSI (Large Scale Integration) permite ubicar 10.000 componentes electrónicos en un chip de 1 cm.\n\n-Gary Kindall, fundador de Digital Research, desarrolla el CP/M, primer sistema operativo para microordenadores.\n\n-IBM comercializa su sistema de disco 3340 Winchester de una capacidad de 30 Mbytes, el precursor de los modernos discos duros."));
        eventoList.add(new Evento("1974", "-Aparecen en el mercado los microprocesadores de 8 bits Intel 8080 y Motorola 6800, utilizados posteriormente como base para la construcción de computadores personales.\n\n-Se publica un artículo en la revista Radio Electronics que describe como construirse un minicomputador personal, el Mark-8.\n\n-Se comercializa la primera memoria RAM dinámica de 4 kbits.\n\n-BBN crea Telenet, el primer servicio público basado en la conmutación de paquetes.\n\n-IBM comercializa un primer intento de PC, el 5100 Personal Portable Computer, implementado con tecnología propia de IBM."));
        eventoList.add(new Evento("1975", "-Aparece en el mercado un kit del primer computador personal de la historia, el ALTAIR 8800 basado en el microprocesador Intel 8080.\n\n-Se comercializan los ordenadores: UNIVAC 1100/10, 1100/20 y 1100/90.\n\n-IBM introduce la impresora láser."));
        eventoList.add(new Evento("1976", "-Seymour Cray construye el Cray-1, primer supercomputador con arquitectura vectorial, que alcanza velocidades de 180 megaflops y ninguno de sus cables de conexión es mayor de 8 pies.\n\n-AMD e Intel firman un acuerdo para compartir licencias.\n\n-IBM desarrolla la impresora de inyección de tinta.\n\n-Steve Jobs y Steve Wozniak diseñan y construyen el Apple I, basado en el microprocesador 6502.\n\n-Shugart Associates y Dysan Corporation desarrollan los disquetes magnéticos de 5 ¼ pulgadas, que tenían una capacidad de menos de 100 kbytes."));
        eventoList.add(new Evento("1977", "-Bill Gates y Paul Allen fundan la empresa Microsoft.\n\n-Varias compañías empiezan a experimentar con cables de fibra óptica.\n\n-Se anuncian y comercializan varios computadores personales: Commodore PET, TRS-80..."));
        eventoList.add(new Evento("1978", "-Se presenta el procesador de textos WordStar, ampliamente utilizado con sistemas CP/M y posteriormente con DOS (Disk Operating System).\n\n-DEC introduce el VAX-11, un computador de 32 bits con un sistema operativo común y compatibilidad entre los productos de la misma línea. Se consideró un estándar para aplicaciones científicas y técnicas.\n\n-Intel presenta el microprocesador de 16 bits, el 8086.\n\n-Se empieza a elaborar el lenguaje ADA, a petición del Departamento de Defensa de EEUU.\n\n-Nicklaus Wirth introduce el MODULA 2.\n\n-A partir de esta fecha aparece una enorme gama de fabricantes de microordenadores: HP, Texas Instrument, Epson, Digital, SINCLAIR..."));
        eventoList.add(new Evento("1979", "-Don Bricklin y Bob Franston desarrollan el VisiCal, la primera hoja de cálculo.\n\n-Intel presenta el microprocesador 8088, de características similares al 8086 pero compatible con sus microprocesadores de 8 bits.\n\n-Motorola introduce el microprocesador 68000, que sería tomado como base para los computadores personales Macintosh.\n\n-En Japón y Chicago se realizan las primeras pruebas con teléfonos móviles."));
        eventoList.add(new Evento("1980", "-Seagate Technology desarrolla el ST506, el primer disco duro para ordenadores personales con una capacidad de 5 Mbytes.\n\n-Sony comercializa la primera unidad de disquetes de 3 ½ pulgadas.\n\n-Tim Patterson, de Seattle Computer Products, escribe un pequeño sistema operativo, el QDOS (Quick and Dirty Operating System,) para ser usado en procesadores Intel 8086. Posteriormente es comprado por Microsoft.\n\n-Se pone en el mercado el computador personal Apple II, dotado de gráficos en color."));
        eventoList.add(new Evento("1981", "-Microsoft renombra el QDOS a MS-DOS (MicroSoft-Disk Operating System). El sistema se monta en el ordenador personal IBM PC, con el nombre de PC-DOS.\n\n-Microsoft comienza el desarrollo de un programa basado en un entorno gráfico, que finalmente se pone a la venta en 1985 con el nombre de Windows 1.0.\n\n-El esfuerzo conjunto de Sony y Philips hace posible la aparición de los videodiscos digitales.\n\n-Aparece el Xerox Star, la versión comercial del prototipo de PC Alto comenzada a desarrollar en el año 1973 por Xerox.\n\n-IBM entra en el mercado de los ordenadores personales con la comercialización de la arquitectura abierta IBM PC y sistema operativo DOS 1.0, lo que supuso un verdadero hito en la historia."));
        eventoList.add(new Evento("1982", "-Columbia Data Produts y Compaq producen las primeras máquinas clónicas del IBM PC.\n\n-Se funda la empresa Autodesk, que un año después pondría en el mercado la primera versión del AutoCAD.\n\n-John Warnock desarrolla el PostScript y forma con Charles Geschke la empresa Adobe Systems.\n\n-Aparece el multiprocesador Cray X-MP, que contenía hasta 4 procesadores tipo Cray-1 conectados en paralelo.\n\n-Se establece un servicio comercial de correo electrónico entre 25 ciudades de los Estados Unidos.\n\n-Se ponen en el mercado máquinas para juegos destinadas al gran público: Spectrum y Commodore 64."));
        eventoList.add(new Evento("1983", "-El IBM PC-XT (eXtended Technology) alcanza un gran éxito comercial.\n\n-Se completa el estándar TCP/IP, que marca el punto de referencia para la creación de Internet.\n\n-Apple lanza al mercado el computador personal Lisa que incorporaba ratón, iconos, y menús desplegables. No tuvo éxito comercial.\n\n-Se fundan las empresas Thinking Machines y Ncube orientadas al desarrollo del procesamiento paralelo.\n\n-Bjarne Stroustrup, de los laboratorios Bell, desarrolla una extensión orientada a objetos del lenguaje C, el C++."));
        eventoList.add(new Evento("1984", "-Sony y Philips definen el estándar del CD-ROM (Compact Disc-Read Only Memory), que se utilizará como sistema de almacenamiento óptico de datos digitales.\n\n-Se introduce el Sistema de Nombres de Dominio (DNS), que facilita la conexión a los ordenadores sin conocer su dirección IP.\n\n-Apple da un gran impulso a las técnicas gráficas con su programa MacPaint.\n\n-Se desarrolla el estándar MIDI para conectar computadores con instrumentos musicales.\n\n-Motorola introduce el microprocesador MC68020, que contenía 250.000 transistores.\n\n-Se pone en el mercado el IBM PC AT, basado en el chip i80286, que se convierte en un estándar.\n\n-Aparece el Apple Macintosh, basado en el microprocesador M68000 con monitor en blanco y negro integrado en la carcasa e interface GUI."));
        eventoList.add(new Evento("1985", "-La National Science Foundation establece cuatro centros de supercomputación\n\n-Se comercializa el supercomputador Cray-2, capaz de alcanzar velocidades máximas de proceso de 1,9 gigaflops.\n\n-Intel pone en el mercado el microprocesador 80386 de 32 bits, que permite la compatibilidad de software desarrollado para microprocesadores anteriores de la misma familia.\n\n-IBM anuncia la primera tarjeta EGA de resolución 640 x 350 y 16 colores."));
        eventoList.add(new Evento("1986", "-AMD introduce la primera memoria EPROM de 1 millón de bits.\n\n-La FCC (Federal Communications Commission) adopta el concepto de “Arquitectura de Red Abierta”.\n\n-IBM lanza el PC Convertible, que puede considerarse el primer laptop. Utiliza un microprocesador i8088 de bajo consumo para prolongar la vida de la batería.\n\n-Larry Wall desarrolla el lenguaje PERL."));
        eventoList.add(new Evento("1987", "-Compaq introduce el primer PC con tarjeta grafica VGA, el “SLT/286”.\n\n-IBM y Microsoft ponen a la venta el sistema operativo OS/2 1.0, similar al MS-DOS, que supone una mejora en el aprovechamiento de los recursos de los procesadores.\n\n-Se pone en el mercado el IBM PS/2, que fue evolucionando tomando como base distintos microprocesadores, desde el 8086 al 80486, y los sistemas operativos OS/2, DOS 3.0 y DOS 4.0."));
        eventoList.add(new Evento("1988", "-Motorola introduce la serie 88000 de microprocesadores RISC capaces de ejecutar 17 millones de instrucciones por segundo.\n\n-El estudiante Robert Morris Jr. Pone en evidencia la necesidad de incrementar la seguridad en las redes lanzando un programa que sobrecarga Internet.\n\n-Se lanza el computador NeXT, diseñado por Steve Jobs, pero aun teniendo características muy avanzadas no tiene éxito comercial."));
        eventoList.add(new Evento("1989", "-Tim Berners-Lee propone el proyecto World Wide Web (WWW) al CERN (Conseil Européene pour Recherche Nucléaire).\n\n-Se lanza al mercado el chip microprocesador de Intel 80486 de 32 bits, que contiene 1,2 millones de transistores y se realizan versiones que alcanzan desde 25 hasta 50 MHz.\n\n-SUN comercializa la SPARC Station, una estación de trabajo de dimensiones similares a las de una caja de pizza.\n\n-Se pone en el mercado el ATARI Portfolio, de dimensiones 20 x 10 x 2,5 cm y 350 gramos de peso. Incluye procesador de textos, hoja de cálculo, agenda, bases de datos y conexión a otras máquinas más potentes."));
        eventoList.add(new Evento("1990", "-Aparece el HTML (HiperText Markup Language), un lenguaje para crear páginas en World Wide Web. No es propiamente un lenguaje de programación sino solo de exhibición de contenidos y navegación.\n\n-El número de usuarios de Internet es de alrededor de unas 500.000 personas en todo el mundo.\n\n-Microsoft introduce el Windows 3.0 e intensifica su disputa legal con Apple por su similitud con el sistema operativo del Macintosh.\n\n-Tim Berners-Lee escribe el prototipo inicial del WWW, utilizando sus desarrollos anteriores: URL, HTML y HTTP."));
        eventoList.add(new Evento("1991", "-Apple, IBM y Motorola empiezan a desarrollar la familia de microprocesadores Power PC.\n\n-SUN comercializa máquinas con estructura RISC y pone a punto el sistema operativo Solaris.\n\n-AMD rompe el monopolio de Intel introduciendo el AMD 386 DX, el primer clónico del Intel 386.\n\n-Linus Torvalds programa como diversión el Linux, una variante del sistema operativo Minix. El código del nuevo sistema operativo, comienza a distribuirse rápidamente de forma gratuita por Internet."));
        eventoList.add(new Evento("1992", "-SUN comercializa la SPARC Station 10, primer computador multiproceso de sobremesa.El virus Michelangelo se distribuye por Internet, causando una gran preocupación entre la comunidad internauta.\n\n-DEC introduce el primer chip para implementar su arquitectura RISC Alpha de 64 bits."));
        eventoList.add(new Evento("1993", "-Intel introduce el Pentium, un microprocesador de 3,1 millones de transistores y 60 MHz de velocidad.\n\n-Se desarrolla el multicomputador Cray T3D, con velocidades entre 25 gigaflops y 1,5 teraflops. Se destina a resolver problemas en los campos de la biología y química, que demandan supercomputación.\n\n-En el Centro Nacional de Supercomputación de la Universidad de Illinois se desarrolla el Mosaic, una interfaz gráfica de usuario para navegación por Internet.\n\n-Se comercializa el IBM ThinkPad 750. El primer “notebook” que viaja al espacio en el trasbordador espacial Endeavour, durante la misión para reparar el telescopio Hubble."));
        eventoList.add(new Evento("1994", "-Jim Clark y Marc Andreesen forman la compañía Netscape Communications y ponen en el mercado la primera versión de su navegador.\n\n-Tras tres años de versiones preliminares, se libera la versión 1.0 del núcleo de Linux."));
        eventoList.add(new Evento("1995", "-Se estrena la película de animación Toy Story, que está realizada complemente por computador.\n\n-Sun Microsystems Inc. crea el Java. Permite el desarrollo de aplicaciones independiente de la plataforma.\n\n-Borland introduce Delphi, un entorno de programación para desarrollo rápido de aplicaciones.\n\n-Nace el DVD (Digital Versatile Disc) ante la necesidad de disponer de un estándar común que incluyese vídeo, audio y datos en un mismo formato.\n\n-Microsoft comercializa la primera versión de Windows como sistema operativo: Windows 95. Su lanzamiento fue apoyado por una espectacular campaña publicitaria.\n\n-Se anuncia el Pentium Pro, que contiene de 5,5 millones de transistores y funciona a 150 MHz velocidad.\n\n-Se calcula que el número de usuarios de Internet en el mundo es de 10 millones de personas."));
        eventoList.add(new Evento("1996", "-Un consorcio de varias compañías hacen posible el desarrollo del CD-RW (Compact Disk ReWritable)."));
        eventoList.add(new Evento("1997", "-Se comercializa el Intel Pentium II, que contiene 7,5 millones de transistores y funciona a velocidades de 233 MHz.\n\n-IBM lanza el ASCI Deep Blue, un supercomputador capaz de evaluar 20 millones de posiciones de ajedrez por segundo. El campeón del mundo Gary Kasparov sólo es capaz de evaluar 3 posiciones por segundo."));
        eventoList.add(new Evento("1998", "-Microsoft pone a la venta Windows 98, una revisión de Windows 95, en la que se corrigen muchos errores de programación y se añaden nuevas funcionalidades.\n\n-Los estudiantes Larry Page y Sergey Brin, de la Universidad de Stanford, crean el motor de búsqueda “PageRank” para rastrear automáticamente direcciones de Internet. Este algoritmo es el corazón del buscador Google."));
        eventoList.add(new Evento("1999", "-Se comercializa el Intel Pentium III. Contiene 28 millones de transistores y funciona a velocidades de 400 MHz.\n\n-AMD pone en el mercado su procesador Athlon."));
        eventoList.add(new Evento("2000", "-El AMD Athlon se convierte en el primer procesador doméstico de 1 GHz. Contiene 37 millones de transistores.\n\n-Los inventores del circuito integrado reciben el Premio Nóbel de Física.\n\nSe lanza al mercado el Intel Pentium 4, realizado con 48 millones de transistores y alcanza velocidades de 1,5 GHz."));
        eventoList.add(new Evento("2001", "-Microsoft unifica sus sistemas operativos enfocados al mercado doméstico y al profesional en un único producto: Windows XP.\n\n-El número de usuarios de alguno de los servicios de Internet es de casi 500 millones de personas en todo el mundo, de las que 120 millones son europeas."));
        return eventoList;
    }
}
